- telethon/network/mtproto_sender.py
- telethon_tests/network_test.py
Fix for #24.
With this changes TelegramClient works more than hour with and without ```update_handler```.
Also found small bug in network test. After fix all tests passed.
> added pings (fix #24)

- README.rst
- telethon/telegram_client.py
- telethon_generator/tl_generator.py
1. Relative imports does not allowed if module was not loaded. This fails manual install
2. `reconnect` flag fails saved session if client was not previously connected
> Doc improvement and force reconnection

- telethon/interactive_telegram_client.py
- telethon/network/mtproto_sender.py
- telethon/network/tcp_client.py
- telethon/telegram_client.py
Such RPC results may arrive after reconnection, for example.
This should fix #69.
> MtProtoSender: Fix crash on receiving unknown RPC results

- telethon/network/tcp_client.py
See for details: https://docs.python.org/3/howto/sockets.html
"When a recv returns 0 bytes, it means the other side has closed (or is in the process of closing) the connection. You will not receive any more data on this connection. Ever."
> Raise an exception if recv() returned 0 bytes

- telethon/interactive_telegram_client.py
Convert strings from UTF-8 to ascii to enable printing in non-compatible shells/terminals with UTF-8.
Non-compatible charaters are removed from the string.
> Enable printing of UTF-8, improvement for #70

- telethon/telegram_bare_client.py
This commit fixes pretty obvious error, by passing str insted int for api_id parameter
```
client = telethon.TelegramClient('phone_number', "api_id", "api_hash")
```
Here is error:
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "C:\Program Files\Python35\lib\site-packages\telethon\telegram_client.py", line 177, in connect
layer=layer, query=query))
File "C:\Program Files\Python35\lib\site-packages\telethon\telegram_client.py", line 326, in invoke
self.sender.send(request)
File "C:\Program Files\Python35\lib\site-packages\telethon\network\mtproto_sender.py", line 63, in send
request.on_send(writer)
File "C:\Program Files\Python35\lib\site-packages\telethon\tl\functions\invoke_with_layer.py", line 34, in on_send
self.query.on_send(writer)
File "C:\Program …
```
> (Fix) Fix api_id type mismatch

- telethon_generator/tl_generator.py
This commit adds to_dict() method, and you can build dict object from each tl object.
Method samples:
```
def to_dict(self):
return {
'pinned': self.pinned, 
'peer': self.peer.to_dict() if self.peer is not None else None, 
'top_message': self.top_message, 
'read_inbox_max_id': self.read_inbox_max_id, 
'read_outbox_max_id': self.read_outbox_max_id, 
'unread_count': self.unread_count, 
'notify_settings': self.notify_settings.to_dict() if self.notify_settings is not None else None, 
'pts': self.pts, 
'draft': self.draft.to_dict() if self.draft is not None else None, 
}
```
```
def to_dict(self):
return {
'messages': [_.to_dict() if _ is not None else None for _ in self.messages] if self.messages is not None else [],
'chats': [_.to_dict() if _ is not None else None for _ in self.chats] if …
```
> (Add) Add to_dict() method

- README.rst
Use absolute url to support reading the READMI.rst on PyPI
> fix broken link in README

- telethon/telegram_client.py
This commit fixes issues, when your update thread exits due to broken tcp or MTProto sessions.
BrokenPipeError - tcp session obtained rst flag or reached timeout
InvalidChecksumError - bad packet crc (it means we lost packet order)
> (Fix) Reconnecting tcp, MTProto sessions, when they are broken

- try_telethon.py
Optionally allow to configure socks_proxy=host:port in api/settings
for try_telethon.py example.
I have found it useful but feel free to close this pull requestion
without merging.
> Support configuring SOCKS proxy in the example

- telethon/network/authenticator.py
the docs say a 2048 bit number. `os.urandom` takes an argument that represents the number of bytes. 2048 bits is 256 bytes
> fix amount of random bytes `b` should be in DH

- telethon/telegram_client.py
If set  instance of `Session` this error happen:
```
File ".../lib/python3.5/site-packages/telethon/telegram_client.py", line 121, in __init__
system_lang_code if system_lang_code else self.session.lang_code
AttributeError: 'TelegramSession' object has no attribute 'lang_code'
```
and if we want to use `JsonSession` this detect as invalid instance
```
ValueError: The given session must be a str or a Session instance.
```
so, problem solved by this PR.
> Fix instance error

- telethon/extensions/tcp_client.py
While client.connect() there was `OSError: [WinError 10038] an operation was attempted on something that is not a socket`
> Catching WinError 10038

- telethon/crypto/cdn_decrypter.py
- telethon/network/connection.py
- telethon/network/mtproto_sender.py
- telethon/telegram_bare_client.py
- telethon/telegram_client.py
- telethon/update_state.py
There used to be a `.create_new_connection()` method, which I doubt nobody used. Now a new thread implies a new temporary connection, they're not cached anymore. Connecting is not an expensive operation anyway, and this works similarly to bot APIs need to make HTTP requests which aren't kept alive.
There is also a new way to work with updates: setting a finite amount of workers. No need to call `.poll()` from the main thread anymore.
> Several parallel connections and update workers

- telethon/utils.py
The recent changes in `utils.find_user_or_chat` broke the use case of finding the users of a given message. Passing `message.id` for `peer` and lists for `users` and `chats` returned `None`, even though the User I was looking for, was part of `users`.
This is for example required after a `GetDifferenceRequest` or `GetHistoryRequest` (e.g. [here](https://github.com/LonamiWebs/Telethon/blob/master/telethon/telegram_client.py#L391)).
> Make find_user_or_chat work for message.id again

- telethon_tests/crypto_test.py
This fixes issue #321. Shown below is the test running successfully (no output).
```
$ cd telethon_tests/
$ python3 crypto_test.py CryptoTests.test_generate_key_data_from_nonce
$ 
```
The primary change made was converting the test nonces from `bytes` to `int`.
> Updated test for key generation via nonces

- telethon/telegram_bare_client.py
- telethon/telegram_client.py
- telethon/tl/session.py
Hello! Well, I did that:) 
With this mod the library can work with my [PySocks fork](https://github.com/Man197/PySocks) to use IPv6 address.
> Added support of ipv6 address (boolean "use_v6" parameter in TelegramClient constructor)

- telethon/telegram_client.py
`date`'s default value is `None`, so this function will crash if `name` is empty and `date` is not provided
> Fixes file downloading error

- telethon/telegram_bare_client.py
- telethon/telegram_client.py
- telethon/tl/custom/__init__.py
- telethon/tl/custom/input_sized_file.py
- telethon/tl/session.py
At least I think this is persistent. More than `inputFile` for sure. Note that I moved the `.upload_file()` and `.download_file()` methods to the `TelegramClient` as it made much more sense now with all this cache thing. I think it's something you wanted @cher-nov.
> Better, truly persistent file cache

- telethon/telegram_client.py
Adding two additional arguments to "get_message_history" to avoid hitting the FloodWaitError.
> Adding batch_size and wait_time arguments to "get_message_history".

- telethon/extensions/tcp_client.py
PySocks when connecting throws ProxyConnectionError if proxy server is unavailable. ProxyConnectionError catchs in OSError block and `e.errno` is `None`, so `getattr(errno, 'WSAEACCES', None) ` is also `None` (i use Linux) and the error is omitted that causes an infinite loop.
> Proxy connection fix

- telethon/telegram_client.py
In Python3, you're unable to send named parameters after **kwargs
> Fix syntax error on Python3

- telethon/telegram_client.py
When i forward message from PM to super-group causes error: 
[`id_to_message` doesn't have `random_to_id[rnd]` key](https://github.com/LonamiWebs/Telethon/blob/master/telethon/telegram_client.py#L852) when incoming update is instance of `UpdateNewChannelMessage`
```
* part of traeback *
File "/home/jrootjunior/PycharmProjects/farm/venv/lib/python3.6/site-packages/telethon/telegram_client.py", line 837, in forward_messages
return [id_to_message[random_to_id[rnd]] for rnd in req.random_id]
File "/home/jrootjunior/PycharmProjects/farm/venv/lib/python3.6/site-packages/telethon/telegram_client.py", line 837, in <listcomp>
return [id_to_message[random_to_id[rnd]] for rnd in req.random_id]
KeyError: 315
```
> Fix forwarding messages to super-groups & channels.

- README.rst
- readthedocs/extra/examples/bots.rst
- readthedocs/extra/examples/chats-and-channels.rst
- readthedocs/extra/examples/working-with-messages.rst
- telethon/events/chataction.py
1. Readme - update deprecated method
2. Extras - Use :tl: objects as much as possible
3. Event.ChatAction - Add action_message to docstring
> Docstrings fixes

- telethon/tl/tlobject.py
Discussed here: [https://github.com/LonamiWebs/Telethon/issues/749](https://github.com/LonamiWebs/Telethon/issues/749)
This will work fine now:
``` python
from telethon.tl.tlobject import TLObject
import pickle
a = TLObject()
b = pickle.dumps(a)
c = pickle.loads(b)
```
> Make TLObject picklable

- telethon/telegram_client.py
Making a client to `log_out()` doesn't remove the authorized status, allowing the client to bypass `client.is_user_authorized()`.
> Changing self._authorized property after log_out()

- telethon/telegram_client.py
As said in https://t.me/TelethonChat/33059 , the "0,1,1" values work better for all kind of videos, instead of the "0,0,0", which gave some problems with videos not recorded by the official apps.
> Better handling of video notes

- readthedocs/telethon.tl.custom.rst
- telethon/events/chataction.py
- telethon/events/common.py
- telethon/events/messageread.py
- telethon/events/newmessage.py
- telethon/telegram_client.py
- telethon/tl/custom/__init__.py
- telethon/tl/custom/message.py
- telethon/tl/custom/messagebutton.py
Likely broken things:
* All `isinstance(x, Message)` will no longer work. Also, `custom.Message` depends on `utils` so we can't use `custom.Message` in `utils`… Unless we somehow could subclass the original `Message` class instead implementing `__getattr__`.
* Update documentation where it says it returns a <code>:tl:\`Message\`</code>. It's a <code>\`telethon.tl.custom.message.Message\`</code> now.
Things to reconsider:
* `events.NewMessage` is pretty much the new `custom.Message`, but the latter is now available everywhere and it has a lot of duplicated functionality. Maybe `events.NewMessage` should subclass `custom.Message`. It makes sense that a new message event is, well, a message.
*__Note to self:__ don't merge this yet.*
> New custom Message class

- telethon/client/telegrambaseclient.py
- telethon/client/updates.py
- telethon/network/mtprotosender.py
Currently, upon disconnection for any reason, the event loop will just hang indefinitely because there is nothing to stop it.
This pull request adds a new interface to MTProtoSender (with a proxy in TelegramBaseClient) in the form of a future that is used to relay the disconnection event, including the error that has caused it when applicable.
It also adds a convenience method to the event API to run the event loop until that future resolves, in order to keep the API easy to use. This method is the equivalent of `idle` in the old threaded API.
> Implement a mechanism to notify of connection failures

- telethon/tl/custom/message.py
Currently the entity and text are zipped. If a cls parameter is passed, the text would have been filtered but the entities list would not be filtered, therefore the text would not correspond with the entity.
> fixing get_entities_text with cls

- telethon/client/uploads.py
I couldn't remove file after `client.send_file(...)`, because it was used by os. 
I found that file was not closed by hachoir extractor and `with` statement did the trick.
> fix: hachoir don't close files by itself

- telethon/__init__.py
- telethon/full_sync.py
This pull request adds a `full_sync` module, which can be used to rewrite all methods in the public interface of the library to delegate asyncio calls to an event loop running in another thread.
Slightly WIP: I haven't quite figured out how to make stopping nice. Can we just tell users to call ~~`asyncio.get_event_loop().stop()`~~ `telethon.full_sync.stop()` when they want to stop?
> Add full_sync module

- telethon/sessions/memory.py
The previous version crashes as the arguments don't get unpacked correctly
> Fix file cache when using MemorySession

- telethon/utils.py
Currently, `utils.get_peer` returns `None` when you give it an `InputPeerSelf` object. 
Additionally `utils.get_peer_id` trusts the value from `get_peer` to not be `None`, so doing `utils.get_peer_id(types.InputPeerSelf())` causes it to raise a rather cryptic error:
I've added a special case for this in utils.get_peer_id as a QoL change.
> Fix for utils.get_peer not raising when passed an InputPeerSelf

- telethon/network/connection/connection.py
The flow in `connect()` is attempting to wrap `self._socket` with SSL, which seem to be some leftover attribute, which does not exist now.
> fix ConnectionHttp ssl socket wrap

- telethon/client/uploads.py
Setting caption to None, like most other optional parameters accept, would throw a ValueError
> Fix caption default inconsistency

- telethon/client/auth.py
Apparently the salt1 you send to the server requires an additional 32 bytes of random data. It's easy to miss this requirement from reading the tdesktop source, because this extension is done in a function called `ValidateNewCloudPasswordAlgo`.
https://github.com/telegramdesktop/tdesktop/blob/2e5a0e056cdb40d61d487c6062bffe1a835f6ddd/Telegram/SourceFiles/core/core_cloud_password.cpp#L210-L211
> Extend new_algo.salt1 to fix edit_2fa

- telethon/__init__.py
- telethon/client/downloads.py
- telethon/client/messages.py
- telethon/client/telegrambaseclient.py
- telethon/client/updates.py
- telethon/client/uploads.py
- telethon/client/users.py
- telethon/extensions/messagepacker.py
- telethon/network/connection/connection.py
- telethon/network/connection/tcpfull.py
- telethon/network/connection/tcpobfuscated.py
- telethon/network/mtprotosender.py
- telethon/network/mtprotostate.py
- telethon/tl/core/messagecontainer.py
- telethon/tl/core/tlmessage.py
Add option to pass own logger instance or name to TelegramBaseClient that is then propagated to everything else.
> Make logger fully configurable

- telethon/client/telegrambaseclient.py
- telethon/network/__init__.py
- telethon/network/authenticator.py
- telethon/network/connection/__init__.py
- telethon/network/connection/connection.py
- telethon/network/connection/tcpfull.py
- telethon/network/connection/tcpmtproxy.py
- telethon/network/connection/tcpobfuscated.py
This (partially) closes #823.
Important notes:
* Implementation is rough due to inconsistencies in the network abstractions in Telethon, hope I'll try to refactor them later.
* This doesn't support dd-secure mode for now since it's damn undocumented and I failed to find any understandable hint.
Reference articles and links that were very helpful:
* English
* https://github.com/alexbers/mtprotoproxy
* https://github.com/9seconds/mtg#secure-mode
* https://blog.susanka.eu/how-telegram-obfuscates-its-mtproto-traffic/
* Russian
* https://telegra.ph/telegram-blocks-wtf-05-26
* https://habr.com/ru/post/359348/
* https://habr.com/ru/post/414099/
* https://habr.com/ru/post/414139/
Many thanks to @aprosvetova aka **koteeq**.
>  Initial implementation of MTProxy connection support

- requirements.txt
- setup.py
- telethon/client/chats.py
- telethon/client/dialogs.py
- telethon/client/messages.py
- telethon/requestiter.py
- telethon/sync.py
**Motivation**:
* Removing an extra dependency with a custom solution may offer an speed up.
* Easier to maintain. The methods were *really* big and this helps separate their logic into more parts.
* IDEs like PyCharm struggle to correctly type hint them (because it sees an `async def`, but it's actually used as an asynchronous generator).
* Reusability. A lot of patterns were being repeated constantly (such as collecting the iterator into a `TotalList`, handling how long to sleep between requests, dealing with the amount of items left to yield, etc.
After 5 hours of work it's mostly done. I spotted a few bugs in the previous implementation:
* `iter_messages` while doing a `search` in `reverse` didn't work. This was fixed.
* `iter_messages` while using too many `ids` wouldn't chunk them. …
> Overhaul asynchronous generators

- telethon/client/telegrambaseclient.py
- telethon/network/__init__.py
- telethon/network/connection/__init__.py
- telethon/network/connection/connection.py
- telethon/network/connection/http.py
- telethon/network/connection/tcpabridged.py
- telethon/network/connection/tcpfull.py
- telethon/network/connection/tcpintermediate.py
- telethon/network/connection/tcpmtproxy.py
- telethon/network/connection/tcpobfuscated.py
Added more ways to connect to mtproto proxy:
Using intermediate and randomized intermediate ("secure mode"/"dd-mode").
Previous implementation of mtproto proxy was refactored to use the same primitives as other implementations.
ConnectionTcpObfuscated was also refactored to make mtproto proxy implementation easier.
Old class hierarchy:
```
Connection(ABC)
TcpIntermediate(Connection)
ConnectionTcpAbridged(Connection)
ConnectionTcpObfuscated(ConnectionTcpAbridged)
ConnectionTcpMTProxy(ConnectionTcpObfuscated)
```
New hierarchy:
```
Connection(ABC)
ConnectionTcpIntermediate(Connection)
ConnectionTcpAbridged(Connection)
ConnectionTcpObfuscated(Connection)
#contains AbridgedPacket() and ObfuscatedIO()
TcpMTProxy(Connection)
ConnectionTcpMTProxyAbridged(TcpMTProxy)
#contains AbridgedPacket() …
```
> Implement different mtproto proxy protocols

- telethon/requestiter.py
There are problems with:
```Traceback (most recent call last)
<ipython-input-25-2ba447b078db> in async-def-wrapper()
1 it = client.iter_messages(entity)
2 with suppress(StopAsyncIteration):
----> 3     chunk = [await it.__anext__()]
4 if it.total > 1:
5     async for message in it:
/usr/local/lib/python3.7/dist-packages/telethon/requestiter.py in __anext__(self)
59                 self.left = len(self.buffer)
60 
---> 61         if self.left <= 0:  # <= 0 because subclasses may change it
62             raise StopAsyncIteration
63 
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
```
The following works correctly:
```python
it = client.iter_messages(entity).__aiter__()
with suppress(StopAsyncIteration):
chunk = [await it.__anext__()]
if it.total > 1:
async for …
```
> Fix RequestIter.__anext__ without __ainit__

- telethon/network/connection/tcpmtproxy.py
Below is the result for the current master. Currently we're cutting off last secret's byte while we're definitely meant to cut the 'dd' part of it.
Here we're able to login after fixing dd part
> Fix mtproxy dd-mode

- telethon/client/chats.py
- telethon/events/callbackquery.py
Both these methods should work regardless of the entity type(group or channel).
If no user is passed to the edit_permission method the group permission will be the one affected.
> Add a convenience method for editing admin rights and permissions

- telethon/client/downloads.py
For example, GrinIn (MongoPy) don't have flush() method.
On previous version of Telethon flush() not used.
> Check exist flush method

- telethon/extensions/binaryreader.py
- telethon/tl/tlobject.py
Some timestamps can be negative, and anything lower than -43200 throws OSError. Handle that by changing the `value == 0` check to `value <= 0`
> Fix negative timestamp issue

- telethon_examples/quart_login.py
As the client seems tied to a specific login, I've changed it from
being a global to a local in the request handler. This should prevent
one user logging in and another unrelated user having access (due to a
global shared client). I've then made use of session storage to store
the phone and code (session storage is per user and deleted when the
browser tab is closed). I wasn't sure if the code was sensitive, if so
it is potentially problematic to store in the default session system
(cookies) - a server storage solution (e.g. redis or in memory) would
be better.
Note that if the client has to be global the Quart before/after
serving functions should be used to connect and disconnect, as so,
client = ...
@app.before_serving
async def startup():
await client.connect()
@app.after_serving …
> Improve Quart example

- telethon/client/chats.py
Previously it was banning users, presumably due to a server side change. Sleeping for 0 doesn't work but sleeping for 0.1 does, so it will do.
> Fix kick_participant in channels

- telethon/client/chats.py
To allow changing your own admin title in groups you own.
> Remove check for InputPeerSelf in edit_admin

- telethon/client/updates.py
Bots can't use messages.getPeerDialogs, so the only way to get the initial channel pts for them is to use getFullChannel.
> Use channels.GetFullChannel instead of messages.getPeerDialogs

- telethon/utils.py
[@ya](https://t.me/ya) has been deleted and therefore should no longer be in the valid usernames regex.
> Remove @ya from the valid usernames

- telethon/tl/custom/messagebutton.py
The HTML entities were getting parsed according to client parse_mode, leading to empty messages and weird entities
> Fix MessageButton.click() with weird strings

- telethon/crypto/rsa.py
this can be seen when using test servers. when fingerprints are None. 
(error was TypeError: cannot unpack non-iterable NoneType object)
> Fix RSA unpacking bug

- telethon/client/messages.py
the `send_message` supports it, but somehow this flag is missing in the `edit_message`.
> edit_message: allow force_document

- .coveragerc
- .github/workflows/python.yml
- dev-requirements.txt
- optional-requirements.txt
- readthedocs/developing/testing.rst
- readthedocs/index.rst
- telethon/client/telegrambaseclient.py
- tests/telethon/crypto/test_rsa.py
- tests/telethon/test_helpers.py
- tox.ini
Add testing configuration:
- pytest as test framework
- tox for creating testing environments and running tests (run with `tox`)
- pytest-asycio for asyncio testing
- coverage/pytest-cov for measuring test coverage
- flake8 for pep8 checking
I've also added one quick example test demonstrating basic unit testing
and use of the basic fixtures and marks provided by pytest-asyncio.
Just this already covers a suprising 32% of the codebase, mostly through
imports, but I wouldn't expect it to be helpful yet. This should provide
a good base to build on in the future though.
> Add example unit test and config for testing

- telethon_generator/generators/errors.py
- tests/telethon/test_pickle.py
The problem is that custom RPCError classes have custom `__init__`s that aren't compatible with the parent. This pull request adds a `__reduce__` for all custom RPCErrors to make them (un)picklable. Might be more optimal to make new base classes or edit the base classes to somehow detect that it's one of the generated RPCErrors, but this works too.
Fixes #749
> Make RPCError subclasses unpicklable again

- telethon/crypto/libssl.py
- telethon/version.py
Hi, this is a regression fix for 8aa15174ab0290c0ad36523147db5fde82f8da4c which breaks macOS again.
As mentioned in the original PR discussion (https://github.com/LonamiWebs/Telethon/pull/1369#issuecomment-589660260), the present code grabs the wrong part of the version number (10 instead of 15, out of '10.15').
I've changed the code slightly to extract the first two numbers and optionally allow dot releases (10.15.4).
> Fix macOS version parsing if dot number is missing

- telethon/network/connection/connection.py
A simple script:
```python
from telethon.sync import TelegramClient
import socks
import logging
logging.basicConfig(level=logging.DEBUG)
api_id = 11111
api_hash = '...'
proxy=(socks.SOCKS4, '127.0.0.1', 9050)
with TelegramClient('anon', api_id, api_hash, proxy=proxy, timeout=60) as client:
print(client.get_me().stringify())
```
The socks proxy is Tor, so it is quite slow.
The script connect to telegram through the proxy and prints user info.
The script fails to connect to the proxy. Log:
```
DEBUG:asyncio:Using selector: EpollSelector
INFO:telethon.network.mtprotosender:Connecting to 149.154.167.51:443/TcpFull...
DEBUG:telethon.network.mtprotosender:Connection attempt 1...
WARNING:telethon.network.mtprotosender:Attempt 1 at connecting failed: ProxyConnectionError: Error connecting to …
```
> Fixed a problem with proxy connection: [Errno 115] Operation now in progress

- readthedocs/developing/telegram-api-in-other-languages.rst
The current documentation left-bar shows all languages being a subtree of C language. This tiny commit fixes that issue.
Problematic:
> fix C language header

- telethon/client/users.py
On the TEST cloud, flood waits do not always include the correct number of seconds. The server sends FLOOD_WAIT_0, so Telethon sleeps 0 seconds before retrying. This leads to a ValueError: Request was unsuccessful 6 times. By making a minimum flood wait duration of 1 second, this error is mitigated, as the delay is long enough to avoid the rapid retries, and the request succeeds on the 2nd attempt. For once, I tested this change, and it fixed the issue.
> Fix SendMessage FloodWaits on TEST cloud

- telethon/utils.py
Hachoir [now supports](https://github.com/vstinner/hachoir/pull/55) creating parsers from byte streams. So we're able to extract metadata from audio/video files that are byte arrays/streams. This fixes the issue where >10MB songs that were byte arrays/streams were sent as files. I'm not sure about videos but since `is_video` returned *False* for byte arrays/streams before, I guess they were sent as files too.
The downside of the solution is that byte arrays/streams have their metadata extracted (using `_get_metadata`) twice: once in `is_audio`/`is_video`, and if one of the two is *True*, then once again inside the condition.
Any feedback you can give me on this would be much appreciated.
> Added extracting metadata from audio/video files with byte array/stream types

- readthedocs/concepts/strings.rst
Added a missing word and changed sentence to use "are" instead of "is".
> Add missing word in docs

- telethon/client/telegrambaseclient.py
Removes rendundant system-type declaration, as it should be specified already when creating an API
Adopts same form of TgDesktop
This could be harmful if someone already has a session with previous data, as telegram could revoke the session
In this case should be adviced using `device_model=platform.uname().system,system_version=platform.uname().release` as arguments
> Improved default session infos

- telethon/client/messages.py
- telethon/client/uploads.py
This pull request adds a parameter for `send_message`, `edit_message` and `send_file` to set custom entities instead of using a text `parse_mode`. While the parse mode can be set to a function, it's a fairly hacky and not type-hinting-friendly solution to pass a non-text `text` and a custom `parse_mode`.
The parameter is named `formatting_entities` instead of `entities` to avoid confusion with the message target `entity`.
> Add parameter to pass raw entities when sending message

- telethon/client/telegrambaseclient.py
- telethon/network/connection/connection.py
In order to select the local ip address (both v4 and v6 tested without proxy) I made the following changes. It's especially usefull if you have several ips available on your system and need to be able to select a specific one.
- I've already tested it successfully with `ConnectionTcpAbridged`, `ConnectionTcpFull`, `ConnectionTcpIntermediate` and `ConnectionTcpObfuscated` for both ipv4 and ipv6
- `ConnectionHttp` didn't work at all for me, even before applying the change (Our company firewall might block it, don't know).
- I was not be able to test `ConnectionTcpMTProxy*`, because I had no such proxy available
The part `s.bind((self._local_addr, None))` for general ip binding on the proxied socket is also not tested because i don't have a running proxy available.
> Add support for local_ip address binding

- telethon/client/telegrambaseclient.py
- telethon/client/updates.py
The call to `get_me()` inside the `_dispatch_update()` was not checked for connection and/or RPC error.
This could lead to unhandled exception inside `_dispatch_update()`, which in turn could lead to unretrievable exception in the future of `_dispatch_update()` and thus, could lead to asyncio warning as in #1589.
> Fix: get_me() inside didn't check for connection / RPC errors

- setup.py
Without the glob, the tests module is still installed using `setup.py install`.
Fixes 4ce2c00, see also #1605
> Actually exclude tests from setup.py installation

- telethon/events/album.py
When i try to forward album:
```python
@client.on(events.Album)
async def album_handler(event):
await event.forward_to(target_username)
```
I have warning:
```
telethon/client/messages.py:894: UserWarning: the as_album argument is deprecated and no longer has any effect
```
So i delete usage of `as_album` kwarg because it deprecated
> Fix UserWarning when forwarding album

- telethon/client/telegrambaseclient.py
Current client implementation does not allow to change proxy without recreating whole `TelegramClient` object.
Instead of creating a new `TelegramClient` each time user needs to change proxy, he can use this method instead.
Pros:
* No need to reopen `Session`
* No cached entities and states are lost
> Add `set_proxy()` method to change proxy, without reestablishing client.

- telethon/crypto/libssl.py
- telethon/version.py
Telethon is not working in macOS Big Sur.
The reason is that macOS Big Sur version is 11.x.y and in telethon we assume the first part is always 10.
> Fix crypto imports on macOS Big Sur

- telethon/utils.py
The new format removed the creator id from it. It is now 0 for compatibility reasons.
> Add new format to resolve invite link

- telethon/client/uploads.py
Though Telegram doesn't support sending album by URL directly, we can upload each photo, get a list of `InputMedia`, and then send them normally using `SendMultiMediaRequest`.
This PR fixes #1408
> Support sending album by URL

- telethon/client/users.py
The `repr()` of TL types is just the class name and pointer, which is pretty much completely useless for any purpose. This changes the error to use `str()` instead, which shows the contents of the entity (i.e. the user ID)
Before:
> ValueError: Could not find the input entity for <telethon.tl.types.PeerUser object at 0x7f7f2e49eaf0>. Please read https://docs.telethon.dev/en/latest/concepts/entities.html to find out more details.
After:
> ValueError: Could not find the input entity for PeerUser(user_id=123456789). Please read https://docs.telethon.dev/en/latest/concepts/entities.html to find out more details.
> Make input entity errors less useless

- telethon/client/messageparse.py
This should improve clarity for issues like #1511 where parsing failure (such as an ampersand in html parsing mode) leads to an error saying:
`ValueError: The message cannot be empty unless a file is provided`
Which is very unclear, and rather misleading
> Improve exception clarity for parsing failure

- telethon/tl/custom/message.py
fix: Message._needed_markup_bot not returning `bot` for the `KeyboardButtonSwitchInline` case when `button.same_peer` is True which is the case for buttons where `switch_inline_query_current_chat` is specified
> fix: Message._needed_markup_bot not returning `bot` in some cases

- telethon/client/updates.py
The typehint for callbacks was pointing to `callable()` which tests if an object is callable. Fixed to use `Callable[[Any], Any]`. We could use `TypeVar` to ensure that the callback takes a subclass of `EventCommon` instead of `Any` but I avoided that as it didn't seem to be common in the codebase.
> Fix typehint for callback in UpdateMethods.

- telethon/sessions/memory.py
Requests like https://tl.telethon.dev/methods/messages/check_chat_invite.html return a https://tl.telethon.dev/constructors/chat_invite_already.html which has a "chat" attribute similar to the "user" attribute other requests have
> Include "chat" attribute in processing entities

- telethon/utils.py
Recently, Telegram changed the invite link format for private groups so they look like `t.me/+InviteHash` instead of the old `t.me/joinchat/InviteHash` format, but the actual invite hashes are the same. Add support for the new "+" format to the username regex.
> Add support for new invite link format

- telethon/_client/chats.py
- telethon/_events/inlinequery.py
- telethon/types/_custom/button.py
`kick_participant` is kept untouched, as kicking a Channel is similar to making no change.
> allow restricting channels

- setup.py
Debian's reproducible builds infrastructure reports that the ordering of
objects listed in the tlobjects dict in /usr/lib/python3/dist-packages/telethon/tl/alltlobjects.py
depends on the filesystem ordering of the *.tl files read at build time.
Fix that by sorting the list in setup.py.
https://reproducible-builds.org/
> setup.py: Make build reproducible by sorting generator input

- telethon_examples/gui.py
use `asyncio` in place of `aio_loop` (fixes #3717)
> fix the gui example

- telethon/_sessions/sqlite.py
This pull request converts `SQLiteSession`'s `session_id` parameter to a string with [`os.fspath`](https://docs.python.org/3/library/os.html#os.fspath) so it works if `session_id` is a [`pathlib.Path`](https://docs.python.org/3/library/pathlib.html) or other [`os.PathLike`](https://docs.python.org/3/library/os.html#os.PathLike) object.
> Add `PathLike` support to `SQLiteSession`

- telethon/_misc/utils.py
This PR fixes `isisintance` to the correct built-in `isinstance` function call in `telethon/_misc/utils.py`.
> Change isisintance to isinstance in utils.py

- telethon/_sessions/string.py
In the `save` method of `StringSession`, if `self.dcs[self.state.dc_id].ipv6` is `None`, `ip` should refer to `self.dcs[self.state.dc_id].ipv4` instead of `self.dcs[self.state.dc_id].ipv6`. Otherwise, an `AttributeError` exception will be raised since a `NoneType` object has no `to_bytes` method.
> Fix IPv6 typo to IPv4 for StringSession.save()
