- telethon/telegram_client.py
> TelegramClient.get_dialogs: Rename 'count' argument to 'limit'

- telethon/telegram_client.py
> TelegramClient: Perform disconnection on class destruction

- telethon_generator/parser/tl_object.py
> Serialize flag_indicator argument to flags:#

- telethon/utils.py
Users may not have set first_name, but last_name only. This commit will remove None from the display name.
> Exclude empty first_name in get_display_name

- telethon/telegram_client.py
There is a problem with log_out function on mac os devices. The problem was discussed here:  https://github.com/veusz/veusz/issues/54 . In this commit I just added a check for OSError
> Fixing log_out problems on mac os devices

- README-long.rst
- README.rst
- telethon/telegram_bare_client.py
- telethon/telegram_client.py
> Let .sign_in() call .send_code_request()

- telethon/errors/rpc_errors_400.py
This rpc error occurs when invoking EditMessageRequest without any contents changes basically.
I'm a newbie for python, Please advise any wrong things if I have missing something.
Sorry for my bad English :sweat:
> Handle RPCError MESSAGE_NOT_MODIFIED (400)

- telethon/errors/rpc_errors_400.py
Username max length is 1+31 = 32
> Fixed username regex

- telethon/telegram_client.py
PR for issue https://github.com/LonamiWebs/Telethon/issues/250
> fix issue  https://github.com/LonamiWebs/Telethon/issues/250

- .gitignore
- telethon/telegram_client.py
- telethon_examples/interactive_telegram_client.py
Added deletion capabilities to both TelegramClient and InteractiveTelegramClient.
> Delete messages in TelegramClient

- telethon/telegram_client.py
- telethon/tl/custom/__init__.py
- telethon/tl/custom/draft.py
> get_drafts() and a custom Draft class

- telethon/telegram_client.py
in method send_message
no returns the sent message if send in channel
need to add UpdateNewChannelMessage
> No returns the sent message

- telethon/telegram_bare_client.py
Not tested, but seems to work. Investigate first.
> Autoreconnect from _invoke fix

- telethon_generator/error_generator.py
> F-String removal

- telethon/network/mtproto_sender.py
- telethon/tl/tl_message.py
Propagated from my asyncio draft. Doesn't checked.
>  Fix: Resend requests on BadServerSalt and BadMsgNotification

- telethon_examples/print_updates.py
This was causing a strange-looking error
> Remove comma

- setup.py
- telethon/__init__.py
- telethon/telegram_bare_client.py
- telethon/version.py
> Fix importing dependencies during installing.

- telethon/extensions/markdown.py
> Proper offset calculation for markdown

- telethon/extensions/html.py
- telethon/telegram_client.py
Not properly tested yet, but it should work.
> Add HTML parse mode

- telethon/session.py
> Save session data when migrating from JSON

- readthedocs/extra/advanced-usage/sessions.rst
Add instructions for use of downloaded session file
> Add further Heroku instructions to session documentation

- telethon/events/__init__.py
Add pattern argument to events.NewMessage. Good for easy command-like interfaces.
> Add pattern argument

- telethon/telegram_client.py
Added new function to allow easy fetching of participants in a group/channel/supergroup
> Added .get_participants(...)

- telethon/events/__init__.py
I changed `event.message.message` to `event.text`, was that okay?
> Capture match and add it to event

- telethon/telegram_client.py
it wasn't async, but it was calling other async methods.
> fix get_participants

- telethon/events/__init__.py
this is a small fix for the reply method in asyncio branch ... there was an `await` missing
> little fix

- telethon/events/__init__.py
> update ChatAction event pins and unpins, fixes #706

- telethon_tests/parser_test.py
- telethon_tests/test_crypto.py
- telethon_tests/test_higher_level.py
- telethon_tests/test_network.py
- telethon_tests/test_parser.py
- telethon_tests/test_tl.py
- telethon_tests/test_utils.py
- telethon_tests/tl_test.py
nothing much yet, still some progress :P
> minor tests cleanup, preparation for travis-ci

- telethon/telegram_client.py
New convenience function to allow easy editing of 2FA settings
> Add edit_2FA function

- telethon/errors/rpc_base_errors.py
Discussed here: [](https://github.com/LonamiWebs/Telethon/issues/749)
> Make RPCError class picklable

- telethon/telegram_bare_client.py
> Cancel background tasks on disconnect

- logo.svg
More seriously I just turned the shadow and main logo into their own single paths and then added a few good practices.
> Make better

- telethon/client/auth.py
Fix for https://github.com/LonamiWebs/Telethon/issues/868
> Keyword arg instead positional for sign_in

- telethon/utils.py
Otherwise, sending voices would fail on some systems.
> Manually register ogg mimetype

- telethon_examples/assistant.py
* Add #spam
* Add #offtopic
* Add #help alias for #list
* Add link to suggestions in #list
> [Assistant] Add #spam, #offtopic, #help and link to suggestions

- telethon/extensions/html.py
- telethon/extensions/markdown.py
this will add the correct formatting to the .text property
> Add name mention formatting to HTML and Markdown

- telethon/client/telegrambaseclient.py
- telethon/network/mtprotosender.py
This will make it sleep x seconds after each retry to space them out.
> Added retry_delay for connection

- telethon/client/messageparse.py
Invalid inline mentions now are sent as normal text.
> Made invalid inline mentions no longer work.

- telethon/client/uploads.py
> Add support Path-like thumb to _file_to_media

- telethon/utils.py
> fixed that thumb is now thumbs

- telethon/client/account.py
> Fix client proxy class for takeouts to access static members properly

- telethon/client/account.py
- telethon/client/telegrambaseclient.py
- telethon/sessions/abstract.py
- telethon/sessions/memory.py
- telethon/sessions/sqlite.py
- telethon/sessions/string.py
Based on this proof-of-concept: https://pastebin.com/kv5dkFnu
> Improve the support for account takeouts

- telethon/client/auth.py
> Fix login failure due to wrong argument name

- telethon/client/telegrambaseclient.py
1st edition: https://github.com/bugchecker/Telethon/commit/6a50cea3958ab84e8dfdff756cb97c49e2621814
> Fix initial state returning by MemorySession.get_update_state

- telethon/events/common.py
> Fix super() initialisation call for EventCommon

- telethon/crypto/libssl.py
This amends the logic introduced for #1167 to only run when a plain import of the library fails, thus avoiding the slow path traversal needed to find the underlying library file.
> Refactor libssl import path workarounds

- telethon/extensions/html.py
Very quickly tested, seems to work. The markdown unparser was too different so I didn't fix that one.
> Add support for unparsing nested entities into HTML

- telethon/events/callbackquery.py
a typo was left unfixed in the last pr
> Small fix for callbackquery

- .gitignore
- default.nix
- nix/ci.nix
- nix/extended.nix
- nix/overlay.nix
- nix/telethon/1.4.nix
- nix/telethon/1.5.nix
- nix/telethon/1.6.nix
- nix/telethon/1.7.nix
- nix/telethon/1.8.nix
- nix/telethon/1.9.nix
- nix/telethon/common.nix
- nix/telethon/devel.nix
- nix/telethon/generator-use-pathlib-to-1_4_3.patch
This is ready enough for merging, I guess. https://github.com/LonamiWebs/Telethon/commit/ae3e42997d7cfb98c0d17ed3e5014478c3dad2ef has the beginnings of CI using this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lonamiwebs/telethon/1246)
> Create Nix package expressions

- telethon/client/uploads.py
Async functions now can be used when uploading files.
> Add async support to upload file prgoress callback

- telethon_generator/data/errors.csv
Update SCHEDULE_DATE_TOO_LATE and -503 description 
New REACTION_EMPTY
> Update SCHEDULE_DATE_TOO_LATE and -503 description

- telethon/events/newmessage.py
> Remove debug code from production

- readthedocs/concepts/entities.rst
- telethon/extensions/html.py
- telethon/network/connection/connection.py
- telethon/network/connection/tcpobfuscated.py
- telethon/tl/custom/adminlogevent.py
just some small typos I found.
> fix small typos

- telethon/client/uploads.py
Fix this problem https://github.com/LonamiWebs/Telethon/issues/1370
> added supports video-albums in send_file

- telethon/crypto/libssl.py
Telethon is currently broken on macOS Catalina (see https://github.com/LonamiWebs/Telethon/issues/1349).
The reason is that macOS 10.15 no longer allows the import of unversioned crypto libraries.
This commit imports code from the [oscrypto library](https://github.com/wbond/oscrypto) with an OS check and inserts library versions if necessary.
The above mentioned issue suggests creating a symlink to circumvent the issue. Even though this works, it is brittle and will frustrate future users who need to search for this hack.
> Fix crypto imports on macOS Catalina

- telethon/client/downloads.py
- telethon/client/uploads.py
This will allow https://github.com/painor/telethon-secret-chat to send/download files correctly from secret chats
> Add encrypted downloads/uploads

- telethon/client/messages.py
> Remove call to `_cache_media`

- telethon/client/messages.py
Hey there.
I made a simple fix for the problem at hand based on your file download code. It's manually tested and seems to work quite well.
For now, I decided to add the functionality in `messages.py`, since this is the only section in the code that actually uses `EditInlineBotMessageRequest`.
However, not implementing this in `UserMethods.__call__` removes other error handling and your retry logic.
But adding this functionality to the generic `__call__` function and thereby bloating this super central  piece of code with an edge-case, seemed somehow dirty and error-prone.
I'm open for any suggestions on where to place this piece of code. I don't know your library's structure well enough to make a good decision.
Fixes #1398
> Fix: Send EditInlineBotMessageRequest to specified datacenter

- telethon/client/chats.py
Fixes https://github.com/LonamiWebs/Telethon/issues/1443
> Fix Chat Action 'song' is alias for 'document' while must be alias for 'audio'

- telethon_examples/README.md
- telethon_examples/payment.py
payment via telethon example (no shipping)
> payment example

- readthedocs/developing/telegram-api-in-other-languages.rst
Hey! Would appreciate adding info about my service Taas to the "other languages" page.
> Add Taas service info

- telethon/client/telegrambaseclient.py
AttributeError: 'TelegramClient' object has no attribute 'loop_create_task'
> Fix typo in docs

- telethon/utils.py
Source: https://t.me/tginfo/2656
> Telegram allows uploading upto 2GB.

- telethon/client/users.py
- telethon/helpers.py
- telethon/network/mtprotosender.py
This is to identify the issue #1556 and partially #1541.
The main error was is in 
`def retry_range(retries):`
> Fix reconnection and retries

- telethon/client/telegrambaseclient.py
- telethon/client/users.py
> Add option to raise last error instead of generic ValueError

- telethon/tl/custom/participantpermissions.py
I commented it on original pr #1575  , but it's not in code so
> Check is_creator for Chats, not only channels

- telethon/tl/custom/message.py
> Message.click() now works with polls

- telethon/utils.py
> Fix get_display_name not getting a name from ChatForbidden

- telethon/client/uploads.py
This implements a new feature in layer 120. Previously it would just send the first file in the list if you passed a list of documents to `send_file`.
> Update send_file to support grouping any file type

- optional-requirements.txt
- readthedocs/basic/signing-in.rst
- telethon/client/telegrambaseclient.py
- telethon/network/connection/connection.py
See discussion at (https://github.com/LonamiWebs/Telethon/pull/1623)
Small fixes for `local_addr` argument.
> Replace PySocks with python-socks for Python >= 3.6

- telethon/tl/custom/participantpermissions.py
due to upgrade to Layer 120
channelParticipantLeft#c3c6796b user_id:int = ChannelParticipant;
> channelParticipantLeft

- telethon/events/common.py
- telethon/events/inlinequery.py
- telethon/events/newmessage.py
I did not propose a lot of changes in this PR. It shall be checked to see if this is a good style for type-hinting so if the style isn't ok, it could get changed easily at the beginning.
#1195
> Add type-hinting: EventBuilder, NewMessage, InlineQuery

- telethon/events/common.py
- telethon/events/inlinequery.py
- telethon/events/messagedeleted.py
- telethon/events/messageedited.py
- telethon/events/messageread.py
- telethon/events/newmessage.py
- telethon/events/newmessage.pyi
- telethon/tl/custom/chatgetter.py
I fixed the bug introduced in the previous PR and added more type-hints.
> Add type-hinting (ChatGetter, Events) and fix bugs

- telethon/crypto/aes.py
- telethon/crypto/aesctr.py
Supercharge your Telethon projects with **TgCrypto** — fast and portable [crypto library](https://github.com/pyrogram/tgcrypto) written in C89.
> Support TgCrypto

- telethon/client/uploads.py
Fixes https://github.com/LonamiWebs/Telethon/issues/3023 issue.
> Fix Md5ChecksumInvalidError for small files

- telethon/client/messages.py
- You can Close this Issue - #3047
> adding attributes, supports_streaming paramters to send_message and edit_message

- readthedocs/concepts/botapi-vs-mtproto.rst
> Minor docs change: less -> fewer

- telethon/tl/custom/button.py
* Added `Button.buy`, which works with `Invoices`.
* Added `Button.game`, which works with `Games`.
* Small More Info of force_reply, `placeholder`.
> Add Button.buy and Button.game

- telethon/client/messages.py
• Added `scheduled` paremeter, which allow itering scheduled messages.
> Filter scheduled messages on iter/get messages method

- telethon/events/chataction.py
> chat action

- readthedocs/concepts/entities.rst
With the intended goal of increasing overall readability, the following changes were made:
- corrected grammar
- corrected spelling
- apply proper punctuation
> (docs): update readthedocs/concepts/entities.rst

- telethon_generator/data/api.tl
TL file was taken from TDLib instead of TDesktop
[1] (https://github.com/tdlib/td/blob/master/td/generate/scheme/telegram_api.tl#L559)
[2] (https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/Resources/tl/api.tl#L569)
> update to layer 138 (again)

- telethon/types/_custom/inlinebuilder.py
title is required and currently raise an error
https://core.telegram.org/bots/api#inlinequeryresultdocument
> fix document result required parameter
